import React from 'react';

// Faint background silhouettes matching the anime aesthetic
export function AnimeBackground() {
  return (
    <div className="fixed inset-0 overflow-hidden pointer-events-none z-0 mix-blend-overlay">
      {/* Tomioka (Left Background) */}
      <svg className="absolute top-[10%] left-[-5%] w-[400px] opacity-[0.08] animate-float-subtle" viewBox="0 0 100 200" fill="#0f766e">
        <path d="M40,50 L50,30 L60,50 L70,90 L60,180 L40,180 L30,90 Z" />
        <path d="M50,30 A10,10 0 1,0 60,30 A10,10 0 1,0 50,30" />
        <path d="M20,70 L40,80 L80,70 L70,80 Z" />
        {/* Haori pattern subtle lines */}
        <line x1="45" y1="90" x2="45" y2="180" stroke="#000" strokeWidth="0.5" />
      </svg>

      {/* Rengoku (Top Right Background) */}
      <svg className="absolute top-[5%] right-[-5%] w-[450px] opacity-[0.10] animate-float-subtle" style={{ animationDelay: '1s' }} viewBox="0 0 100 200" fill="#ea580c">
        <path d="M45,40 L50,20 L55,40 L70,90 L65,190 L35,190 L30,90 Z" />
        <path d="M50,20 C40,0 60,0 50,20" />
        <path d="M25,65 L45,75 L85,60 L75,75 Z" />
        <polygon points="50,40 40,60 60,60" fill="#dc2626" />
      </svg>

      {/* Shinobu (Bottom Left Background) */}
      <svg className="absolute bottom-[2%] left-[10%] w-[350px] opacity-[0.09] animate-float-subtle" style={{ animationDelay: '2s' }} viewBox="0 0 100 200" fill="#7e22ce">
        <path d="M40,40 C45,20 55,20 60,40 L70,100 L55,180 L45,180 L30,100 Z" />
        <path d="M20,60 C40,40 60,40 80,60 C70,70 30,70 20,60 Z" />
      </svg>

      {/* Uzui (Bottom Right Background) */}
      <svg className="absolute bottom-[5%] right-[15%] w-[380px] opacity-[0.08] animate-float-subtle" style={{ animationDelay: '3s' }} viewBox="0 0 100 200" fill="#334155">
        <path d="M35,35 L50,15 L65,35 L80,100 L60,190 L40,190 L20,100 Z" />
        <circle cx="50" cy="15" r="10" />
        <path d="M15,55 L45,60 L85,50 L75,65 Z" />
      </svg>
    </div>
  );
}

// Prominent Hero Silhouettes
export function AnimeHeroes() {
  return (
    <div className="fixed inset-0 overflow-hidden pointer-events-none z-0">
      {/* Tanjiro Left Hero */}
      <div className="absolute bottom-[-5%] left-[-2%] opacity-20 drop-shadow-xl animate-breathing-water">
        <svg viewBox="0 0 200 400" className="w-[300px] h-[500px] max-w-[30vw] min-w-[250px]">
          <defs>
            <linearGradient id="tanjiroGrad" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor="#0d9488" />
              <stop offset="100%" stopColor="#020617" />
            </linearGradient>
          </defs>
          <path d="M90,70 L100,40 L110,70 L140,160 L120,380 L80,380 L60,160 Z" fill="url(#tanjiroGrad)" />
          {/* Scarf / Katana */}
          <path d="M70,120 L180,90 L170,95 L90,130 Z" fill="#fff" opacity="0.8" />
          <path d="M100,50 A15,15 0 1,0 120,50 A15,15 0 1,0 100,50" fill="url(#tanjiroGrad)" />
          {/* Checkered pattern hint */}
          <rect x="80" y="200" width="10" height="10" fill="#0f766e" />
          <rect x="90" y="210" width="10" height="10" fill="#0f766e" />
          <rect x="100" y="200" width="10" height="10" fill="#0f766e" />
          <rect x="110" y="210" width="10" height="10" fill="#0f766e" />
        </svg>
      </div>

      {/* Nezuko Right Hero */}
      <div className="absolute bottom-[-2%] right-[-2%] opacity-20 drop-shadow-xl animate-breathing-flame" style={{ animationDelay: '1s' }}>
        <svg viewBox="0 0 200 400" className="w-[280px] h-[480px] max-w-[28vw] min-w-[220px]">
          <defs>
            <linearGradient id="nezukoGrad" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor="#db2777" />
              <stop offset="100%" stopColor="#020617" />
            </linearGradient>
          </defs>
          <path d="M85,80 L100,50 L115,80 L140,180 L120,400 L80,400 L60,180 Z" fill="url(#nezukoGrad)" />
          <path d="M100,50 A18,18 0 1,0 120,50 A18,18 0 1,0 100,50" fill="url(#nezukoGrad)" />
          {/* Hair flow */}
          <path d="M115,80 C150,150 180,250 160,350" fill="none" stroke="url(#nezukoGrad)" strokeWidth="15" strokeLinecap="round" />
          <path d="M85,80 C50,150 20,250 40,350" fill="none" stroke="url(#nezukoGrad)" strokeWidth="15" strokeLinecap="round" />
          {/* Bamboo muzzle hint */}
          <rect x="95" y="65" width="25" height="8" rx="4" fill="#22c55e" transform="rotate(-10 95 65)" />
        </svg>
      </div>
    </div>
  );
}

// Button Icon Overlays
export function HostRengokuIcon() {
  return (
    <div className="relative flex items-center justify-center w-16 h-16 pointer-events-none">
      {/* Background Particles generated by CSS */}
      {Array.from({ length: 6 }).map((_, i) => (
        <div key={i} className="flame-particle" style={{
          left: `${10 + Math.random() * 80}%`,
          animationDelay: `${Math.random() * 2}s`,
          width: `${4 + Math.random() * 6}px`,
          height: `${4 + Math.random() * 6}px`
        }} />
      ))}
      <svg viewBox="0 0 100 100" className="w-12 h-12 absolute animate-breathing-flame drop-shadow-md z-10" fill="#ea580c">
        {/* Flame Hashira symbol / Silhouette */}
        <path d="M50,10 C40,40 10,50 30,70 C40,80 60,80 70,70 C90,50 60,40 50,10 Z" />
        <path d="M50,20 C45,40 25,45 40,60 C45,65 55,65 60,60 C75,45 55,40 50,20 Z" fill="#facc15" />
      </svg>
    </div>
  );
}

export function JoinTanjiroIcon() {
  return (
    <div className="relative flex items-center justify-center w-16 h-16 pointer-events-none">
      {/* Water Ripples generated by CSS */}
      <div className="water-ripple-aura" />
      <div className="water-ripple-aura" />
      <svg viewBox="0 0 100 100" className="w-12 h-12 absolute animate-breathing-water drop-shadow-md z-10" fill="#0ea5e9">
        {/* Water Wave breathing symbol */}
        <path d="M10,50 C30,30 50,70 70,50 C80,40 90,50 90,50 C90,50 70,90 40,70 C20,50 10,50 10,50 Z" />
        <path d="M20,40 C40,20 60,60 80,40 C85,35 90,40 90,40 C90,40 70,80 50,60 C30,40 20,40 20,40 Z" fill="#38bdf8" />
        <circle cx="50" cy="50" r="10" fill="#0284c7" />
      </svg>
    </div>
  );
}
